name: test_manual_macos_commands

on: workflow_dispatch
  
jobs:
  macos-13:
    runs-on: macos-13
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install commands
        run: |
          brew --version

      - name: run macos commands
        run: ./tools/for_workflow/for_macos-13.sh
